# This is a basic workflow to help you get started with Actions

name: DemoChalenges

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'google.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy Dev
    
  deploy-hml:
    runs-on: ubuntu-latest
    environment:
      name: hml
      url: 'google.com'
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo hml production
        
  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: 'google.com'
    needs: deploy-hml
    steps:
      - name: Run a one-line script
        run: echo Deploy production
